"""add due_date and reminder_sent to bills

Revision ID: 024d3949f302
Revises: e25130905b24
Create Date: 2026-07-16 11:14:42.632469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024d3949f302'
down_revision = 'e25130905b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
