"""add consultation_type and meeting_link to appointments

Revision ID: 90cf468cb040
Revises: 07000abee94c
Create Date: 2026-07-13 17:59:32.840519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90cf468cb040'
down_revision = '07000abee94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_type', sa.String(length=20), nullable=False, server_default='in_person'))
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('consultation_type')

    # ### end Alembic commands ###