"""add cahannel to bills

Revision ID: add1984b5f32
Revises: 024d3949f302
Create Date: 2026-07-17 10:47:06.686350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add1984b5f32'
down_revision = '024d3949f302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=20), nullable=False, server_default='counter'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('channel')

    # ### end Alembic commands ###
