"""Add unique constraint to prevent double-booking

Revision ID: b51638fcb948
Revises: 8a8a17fde250
Create Date: 2026-07-11 10:36:46.826868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51638fcb948'
down_revision = '8a8a17fde250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('uq_doctor_date_slot_active', ['doctor_id', 'appointment_date', 'time_slot'], unique=True, sqlite_where=sa.text("status IN ('PENDING', 'APPROVED')"), postgresql_where=sa.text("status IN ('PENDING', 'APPROVED')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('uq_doctor_date_slot_active', sqlite_where=sa.text("status IN ('PENDING', 'APPROVED')"), postgresql_where=sa.text("status IN ('PENDING', 'APPROVED')"))

    # ### end Alembic commands ###
