"""add prescription_id to bills

Revision ID: e25130905b24
Revises: 90cf468cb040
Create Date: 2026-07-14 21:03:56.502991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25130905b24'
down_revision = '90cf468cb040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bills_prescription_id', 'prescriptions', ['prescription_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bills_prescription_id', type_='foreignkey')
        batch_op.drop_column('prescription_id')

    # ### end Alembic commands ###